SCHEME STDERR
MARKER RSID
ALLELE EffectAllele OtherAllele
EFFECT B
PVALUE P
STDERR SE
CUSTOMVARIABLE N
LABEL N as N


PROCESS workflow/metal_benchmark/accident.tsv
PROCESS workflow/metal_benchmark/adenocarcinoma.tsv
PROCESS workflow/metal_benchmark/agefirstbirth.tsv
PROCESS workflow/metal_benchmark/agelastbirth.tsv
PROCESS workflow/metal_benchmark/alcoholabuse18.tsv
PROCESS workflow/metal_benchmark/alcoholdep.tsv
PROCESS workflow/metal_benchmark/anemia.tsv
PROCESS workflow/metal_benchmark/atrialfib.tsv
PROCESS workflow/metal_benchmark/cancerskin.tsv
PROCESS workflow/metal_benchmark/childmal.tsv
PROCESS workflow/metal_benchmark/cholesterol.tsv
PROCESS workflow/metal_benchmark/chronicpain.tsv
PROCESS workflow/metal_benchmark/chronotype.tsv
PROCESS workflow/metal_benchmark/coffee.tsv
PROCESS workflow/metal_benchmark/contrapill.tsv
PROCESS workflow/metal_benchmark/copd.tsv
PROCESS workflow/metal_benchmark/coronaryartdis.tsv
PROCESS workflow/metal_benchmark/covid.tsv
PROCESS workflow/metal_benchmark/crp.tsv
PROCESS workflow/metal_benchmark/deathofrelative.tsv
PROCESS workflow/metal_benchmark/diabloodpres.tsv
PROCESS workflow/metal_benchmark/dietvariation.tsv
PROCESS workflow/metal_benchmark/disability.tsv
PROCESS workflow/metal_benchmark/divorce.tsv
PROCESS workflow/metal_benchmark/erectile.tsv
PROCESS workflow/metal_benchmark/estradiol.tsv
PROCESS workflow/metal_benchmark/executivefun.tsv
PROCESS workflow/metal_benchmark/exercise.tsv
PROCESS workflow/metal_benchmark/externalizing.tsv
PROCESS workflow/metal_benchmark/financialdiff.tsv
PROCESS workflow/metal_benchmark/fish.tsv
PROCESS workflow/metal_benchmark/fluidintelligence.tsv
PROCESS workflow/metal_benchmark/fruit.tsv
PROCESS workflow/metal_benchmark/gestationduration.tsv
PROCESS workflow/metal_benchmark/hdl.tsv
PROCESS workflow/metal_benchmark/health.tsv
PROCESS workflow/metal_benchmark/healthhappy.tsv
PROCESS workflow/metal_benchmark/healthspan.tsv
PROCESS workflow/metal_benchmark/heartvaria.tsv
PROCESS workflow/metal_benchmark/herpes.tsv
PROCESS workflow/metal_benchmark/hivsuscep.tsv
PROCESS workflow/metal_benchmark/hyperthyroidism.tsv
PROCESS workflow/metal_benchmark/hypothyroidism.tsv
PROCESS workflow/metal_benchmark/il6.tsv
PROCESS workflow/metal_benchmark/illnesses.tsv
PROCESS workflow/metal_benchmark/income.tsv
PROCESS workflow/metal_benchmark/infantmortal.tsv
PROCESS workflow/metal_benchmark/irbd.tsv
PROCESS workflow/metal_benchmark/ldl.tsv
PROCESS workflow/metal_benchmark/loneliness.tsv
PROCESS workflow/metal_benchmark/lupus.tsv
PROCESS workflow/metal_benchmark/magnesium.tsv
PROCESS workflow/metal_benchmark/manager.tsv
PROCESS workflow/metal_benchmark/menarche.tsv
PROCESS workflow/metal_benchmark/menopause.tsv
PROCESS workflow/metal_benchmark/metabolicsyn.tsv
PROCESS workflow/metal_benchmark/nightshifts.tsv
PROCESS workflow/metal_benchmark/nonhdl.tsv
PROCESS workflow/metal_benchmark/numberchildren.tsv
PROCESS workflow/metal_benchmark/offspringbirthweight.tsv
PROCESS workflow/metal_benchmark/ovulating.tsv
PROCESS workflow/metal_benchmark/oxyuptake.tsv
PROCESS workflow/metal_benchmark/parentlife.tsv
PROCESS workflow/metal_benchmark/parentlongevity.tsv
PROCESS workflow/metal_benchmark/partner.tsv
PROCESS workflow/metal_benchmark/pelvicorganprol.tsv
PROCESS workflow/metal_benchmark/peripheralartdis.tsv
PROCESS workflow/metal_benchmark/physactivity.tsv
PROCESS workflow/metal_benchmark/pregnantermin.tsv
PROCESS workflow/metal_benchmark/pulsepress.tsv
PROCESS workflow/metal_benchmark/rheuma.tsv
PROCESS workflow/metal_benchmark/riskbehavior.tsv
PROCESS workflow/metal_benchmark/sinusitis.tsv
PROCESS workflow/metal_benchmark/sleepduration.tsv
PROCESS workflow/metal_benchmark/smokingmaternal.tsv
PROCESS workflow/metal_benchmark/staphylococcus.tsv
OUTFILE workflow/metal_benchmark/file_ .tbl
ANALYZE
