SCHEME STDERR
MARKER RSID
ALLELE EffectAllele OtherAllele
EFFECT B
PVALUE P
STDERR SE
FREQ EAF
AVERAGEFREQ ON
CUSTOMVARIABLE N
LABEL N as N
CUSTOMVARIABLE INFO
LABEL INFO as INFO
   
PROCESS workflow/metal_benchmark/AGDS.tsv
PROCESS workflow/metal_benchmark/ALSPAC.tsv
PROCESS workflow/metal_benchmark/Airwave.tsv
PROCESS workflow/metal_benchmark/BASIC.tsv
PROCESS workflow/metal_benchmark/BioVU.tsv
PROCESS workflow/metal_benchmark/DBDS.tsv
PROCESS workflow/metal_benchmark/ESTBB.tsv
PROCESS workflow/metal_benchmark/EXCEED.tsv
PROCESS workflow/metal_benchmark/FinnGen.tsv
PROCESS workflow/metal_benchmark/GERA.tsv
PROCESS workflow/metal_benchmark/GenScot.tsv
PROCESS workflow/metal_benchmark/HUNT.tsv
PROCESS workflow/metal_benchmark/MVP.tsv
PROCESS workflow/metal_benchmark/MoBa1.tsv
PROCESS workflow/metal_benchmark/MoBa2.tsv
PROCESS workflow/metal_benchmark/MoBa3.tsv
PROCESS workflow/metal_benchmark/PBK.tsv
PROCESS workflow/metal_benchmark/PREFECT.tsv
PROCESS workflow/metal_benchmark/SHARE.tsv
PROCESS workflow/metal_benchmark/STAGE.tsv
PROCESS workflow/metal_benchmark/UKBB.tsv
PROCESS workflow/metal_benchmark/antpo.tsv
PROCESS workflow/metal_benchmark/bidi1.tsv
PROCESS workflow/metal_benchmark/boma.tsv
PROCESS workflow/metal_benchmark/cardm.tsv
PROCESS workflow/metal_benchmark/cof3.tsv
PROCESS workflow/metal_benchmark/col3.tsv
PROCESS workflow/metal_benchmark/deCODE.tsv
PROCESS workflow/metal_benchmark/edi2.tsv
PROCESS workflow/metal_benchmark/emcbp.tsv
PROCESS workflow/metal_benchmark/formm.tsv
PROCESS workflow/metal_benchmark/gens.tsv
PROCESS workflow/metal_benchmark/gep3.tsv
PROCESS workflow/metal_benchmark/grdg.tsv
PROCESS workflow/metal_benchmark/grnd.tsv
PROCESS workflow/metal_benchmark/gsk2.tsv
PROCESS workflow/metal_benchmark/gsmse.tsv
PROCESS workflow/metal_benchmark/gsrdf.tsv
PROCESS workflow/metal_benchmark/gsrdg.tsv
PROCESS workflow/metal_benchmark/gsrdi.tsv
PROCESS workflow/metal_benchmark/gsrdp.tsv
PROCESS workflow/metal_benchmark/i2b3.tsv
PROCESS workflow/metal_benchmark/iPSYCH2012.tsv
PROCESS workflow/metal_benchmark/iPSYCH2015.tsv
PROCESS workflow/metal_benchmark/ihseu.tsv
PROCESS workflow/metal_benchmark/iruts.tsv
PROCESS workflow/metal_benchmark/janpy.tsv
PROCESS workflow/metal_benchmark/lgic2.tsv
PROCESS workflow/metal_benchmark/mazdr.tsv
PROCESS workflow/metal_benchmark/mmi2.tsv
PROCESS workflow/metal_benchmark/mmo4.tsv
PROCESS workflow/metal_benchmark/mrive.tsv
PROCESS workflow/metal_benchmark/muen2.tsv
PROCESS workflow/metal_benchmark/muspc.tsv
PROCESS workflow/metal_benchmark/nes1.tsv
PROCESS workflow/metal_benchmark/pfm2.tsv
PROCESS workflow/metal_benchmark/prote.tsv
PROCESS workflow/metal_benchmark/qi3c.tsv
PROCESS workflow/metal_benchmark/qi6c.tsv
PROCESS workflow/metal_benchmark/qio2.tsv
PROCESS workflow/metal_benchmark/rad3.tsv
PROCESS workflow/metal_benchmark/rage.tsv
PROCESS workflow/metal_benchmark/rai2.tsv
PROCESS workflow/metal_benchmark/rau2.tsv
PROCESS workflow/metal_benchmark/rde4.tsv
PROCESS workflow/metal_benchmark/roc3.tsv
PROCESS workflow/metal_benchmark/rot4.tsv
PROCESS workflow/metal_benchmark/shp0.tsv
PROCESS workflow/metal_benchmark/shpt.tsv
PROCESS workflow/metal_benchmark/stm2.tsv
PROCESS workflow/metal_benchmark/tkda1.tsv
PROCESS workflow/metal_benchmark/topmd.tsv
PROCESS workflow/metal_benchmark/trail.tsv
PROCESS workflow/metal_benchmark/twg2.tsv
PROCESS workflow/metal_benchmark/yapeu.tsv
OUTFILE workdir/metal_benchmark/file_ .tbl
ANALYZE